"""
Django settings for project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-7jvqr4hd--qanf#5ub6c0_+d_=^7i1o$i%g5vx1(drx3d+w(%^"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    # 'django.contrib.admin',
    # 'django.contrib.auth',
    # 'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    # 'django.contrib.staticfiles',
    'core_cache',
    'core_mq',
    'core_task',
]

MIDDLEWARE = [
    # 'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'server.utils.middleware.gate.GateMiddleware',
    'server.utils.middleware.response.ResponseMiddleware'
]

ROOT_URLCONF = "server.urls"

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

WSGI_APPLICATION = "server.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR.parent / 'db.sqlite3',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = "zh-hans"

# TIME_ZONE = 'UTC'
TIME_ZONE = "Asia/Shanghai"

# USE_I18N = True
USE_I18N = False

# USE_L10N = True
USE_L10N = False

# USE_TZ = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
# STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ########################################################################
LOGGING_DIR = BASE_DIR.parent / 'logs'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[%(asctime)s] - %(levelname)s - %(name)s@%(lineno)d: %(message)s'
        },
        'default': {
            'format': '[%(asctime)s] - %(levelname)s - %(x_trace_id)s - %(name)s@%(lineno)d: %(message)s',
        },
        'standard': {
            'class': 'lib.log.formatters.JsonFormatter',
        },
    },
    'filters': {
        'context': {
            '()': 'lib.log.filters.ContextFilter'
        },
        'discard': {
            '()': 'lib.log.filters.DiscardFilter'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
            'filters': ['context'],
            'level': 'DEBUG',
        },
        'file': {
            'class': 'lib.log.handlers.TimedRotatingFileHandler',
            'formatter': 'standard',
            'filters': ['context'],
            'level': 'DEBUG',
            'filename': LOGGING_DIR / 'app.log',
            'when': 'D',
            'backup_count': 3,
        },
        'null': {
            'class': 'logging.StreamHandler',
            'filters': ['discard'],
            'level': 'INFO',
        },
        'task': {
            'class': 'lib.log.handlers.TimedRotatingFileHandler',
            'formatter': 'standard',
            'level': 'DEBUG',
            'filename': LOGGING_DIR / 'task.log',
            'when': 'D',
            'backup_count': 3,
        },
        'mq': {
            'class': 'lib.log.handlers.TimedRotatingFileHandler',
            'formatter': 'standard',
            'level': 'DEBUG',
            'filename': LOGGING_DIR / 'mq.log',
            'when': 'D',
            'backup_count': 3,
        },
        'pika': {
            'class': 'lib.log.handlers.TimedRotatingFileHandler',
            'formatter': 'standard',
            'level': 'DEBUG',
            'filename': LOGGING_DIR / 'pika.log',
            'when': 'D',
            'backup_count': 3,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['null'],
            'propagate': False,
        },
        'core_task': {
            'handlers': ['task'],
            'level': 'INFO',
            'propagate': False,
        },
        'core_mq': {
            'handlers': ['mq', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'pika': {
            'handlers': ['pika'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# Redis config
REDIS_CONF = {
    'host': 'localhost',
    'port': 6379,
    'db': 0,
    'password': 'xxx',
    'max_connections': 2 ** 6
}

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_pro',
        'HOST': 'localhost',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': 'mysql123',
        'CONN_MAX_AGE': 60,
        'OPTIONS': {},
    }
}

# RabbitMQ
RABBITMQ_CONF = {
    'host': 'localhost',
    'port': 5672,
    'vhost': '/local',
    'username': 'username',
    'password': 'password',
    'heartbeat': 0,
    #
    'exchange_map': {
        'task': {
            'exchange_info': {
                'exchange': 'task',
                'exchange_type': 'topic',
                'durable': True,
            },
            'queue_info_list': [
                {
                    'queue': 'task',
                    'routing_keys': ['task.#'],
                    'count': 3,
                },
            ]
        }
    }
}
